name: Compile emcc

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install emcc
      run: sudo apt-get install -y emscripten

    - name: Check emcc version
      run: emcc -v

    - name: Compile C to HTML,
      run: em++ scanf.c -o index.html
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: filez
        path: .
