name: Compile emcc

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Emscripten
      run: sudo apt-get update && sudo apt-get install -y emscripten

    - name: Check Emscripten version
      run: emcc --version

    - name: Compile C to object file
      run: |
        echo "Compiling C to object file..."
        emcc hello.c -o hello.o -s WASM=1
        echo "Compilation completed."

    - name: Link object file to HTML, JS and WASM
      run: |
        echo "Linking object file to HTML, JS and WASM..."
        emcc hello.o -o hello.html --preload-file hello.wasm
        echo "Linking completed."

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: compiled-files
        path: ./
