name: Build SDL2 and SDL2_ttf Project

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          sudo apt-get install -y emscripten
          sudo apt-get install -y libsdl2-dev libsdl2-ttf-dev
      - name: Build SDL2 Project
        run: |
          sudo emcc sdl2.c -o sdl2.html -s USE_SDL=2 -s FULL_ES3=1 -s USE_SDL_TTF=2 \
            -I/usr/include/SDL2 \
            -L/usr/lib/x86_64-linux-gnu \
            -lSDL2 -lSDL2_ttf
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Compiled Files
          path: ./
