name: Compile emcc

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install emcc
      run: sudo apt-get install -y emscripten  
    - name: Install sdl2 
      run: sudo apt-get install -y libsdl2-dev libsdl2-2.0-0
    - name: Check emcc version
      run: emcc -v

    - name: Compile C to html
      run: emcc sdl2.c -o index.html `sdl2-config --cflags --libs` -lSDL2



    - name: Upload compiled Html
      uses: actions/upload-artifact@v3
      with:
        name: index.html
        path: ./index.html
