name: Compile emcc

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install emcc
      run: sudo apt-get install -y emscripten  

    - name: version emcc
      run: ./emcc -v
      
    -name: Compile C to html
    run: ./emcc hello.c -o hello.html
      
  -name: Upload compile Html   
  uses: actions/upload-artifact@v3
          with:
        name: hello.html
        path: ./hello.html
        
